### ISSUE TITLE
How to stop hazard lights from flashing when driving along?

### ISSUE THREAD

**Issue by coatsy35** [Stephan-S/FS22_AutoDrive#1118]
as per title. All of my vehicles when driving on AD have their hazard lights flashing. How do you stop this?

**Comment by Iwan1803** [comment]
Deactivate it in the AD options.

**Comment by coatsy35** [comment]
Where? The only one I see is for reversing?

**Comment by Iwan1803** [comment]
Sorry, translation error... i thought you meant the rotating beacon.
The hazard lights are only activated automatically on fields, not on streets and yes, you can change only the option for driving backwards.

**Comment by coatsy35** [comment]
They are activated on streets, I have a lot of vehicles where they flash as they are driving forward on the streets. Is it a mod error?

**Comment by Iwan1803** [comment]
Try a vanilla vehicle. This shouldn't flash on streets.

**Comment by toralt** [comment]
on my map (NF-Marsh) the beacon lights are all flashing when driving on streets. But the option is deactivated. I have 9 autodrive drivers . I was not from the beginning. I think it started when I started my big load and deliver session with 9 drivers. Since then it always start even with one driver

**Comment by Axel32019** [comment]
no update -> closed
