### ISSUE TITLE
Tractor not stopping under pipe

### ISSUE THREAD

**Issue by JustDen1234** [Stephan-S/FS22_AutoDrive#1138]
During unloading combine, the driver in the tractor with wagon, drives underneath the pipe but does not stop.
Using CP and AD. Combine stops to unload (CP setting), pipe goes out, AD driver drives to pipe but does not stop.

Combinations not working:
- New Holland T8.410 Genesis + Rudolph TDK 301 RA
- John Deere T560 (combine) + John Deere 625X

AD Setting combine:  Pipe offset 0.2m

If i use the Case HI Maxxum CVX 115 instead of the NH Genesis, it stops just in time.
![image](https://github.com/Stephan-S/FS22_AutoDrive/assets/68871402/3b19aafb-2a0f-4d2c-ad87-e5133eb3daba)

Another combination that does not work:
- Fendt 1050 + Rudolph TDK 301 RA
- New Holland CH7.70 (combine) + New Holland Varifeed 28FT
Here again, using the Fendt Favorit 511c works.

AD: v2.0.1.6
CP: v7.4.1.3

**Comment by Axel32019** [comment]
The problem is not the tractor, but the Rudolph TDK 301 RA. It has the exactFillRootNode at the very far end of the loading area which is the point AD matches with the pipe. Depending on tractor speed, acceleration, break force etc. it might come to match or not.
Recommendation: Use Rudolph TDK 301 RP instead, where exactFillRootNode is in the middle of the loading area.

**Comment by JustDen1234** [comment]
Thanks for the explanation !
