### ISSUE TITLE
destination not attached to accessible network crashes F22

### ISSUE THREAD

**Issue by Mobius104** [Stephan-S/FS22_AutoDrive#203]
This happens in all drive modes as far as I can tell.  If the destination waypoint is not attached to the road network currently accessible to the vehicle (not just unable to plot route to that point, but it's completely detached and inaccessible from where the vehicle currently is) then FS22 freezes and crashes if the drive button is pressed rather than giving the unable to plot route error or saying destination not found.     This is with latest version v2.0.0.2.

**Comment by Iwan1803** [comment]
Latest version is 2.0.0.3 😉
Please update and if this happens again, then please post your log file and your AD config.

**Comment by mbooz** [comment]
I can confirm this happens with 2.0.0.3.  AD worked fine for days but kept crashing after only a few minutes recently.  I noticed one of my vehicles kept saying it could not reach a repair point and I kept dismissing it.  I do not repair this vehicle since I just use it to unload combines and deposit in silo.  However after emptying a combine the game would crash every time 15-30s after departing from the combine's location, without giving me the "repair point not found" message.  After reading the issue here and thinking the "repair messages" were my problem, I repaired the vehicle manually and the game has not crashed since.

**Comment by Iwan1803** [comment]
@mbooz did you know that you can deactivate the automatic repair function? 😉

**Comment by mbooz** [comment]
I do but that doesn't really help with crashing the game when it's on and unreachable.

**Comment by Iwan1803** [comment]
Please attach the whole log as it could contains other informations or errors.

**Comment by Axel32019** [comment]
fixed: https://github.com/Stephan-S/FS22_AutoDrive/releases/tag/2.0.0.4
Server crash if several non connected route networks exist #237
