### ISSUE TITLE
train crossing

### ISSUE THREAD

**Issue by velendier** [Stephan-S/FS22_AutoDrive#222]
I just had a tractor get yeeted by a train, is it possible to add a way point to do a check to see if train guards are down with out having collision on.

**Comment by Axel32019** [comment]
Please have a look here #176

**Comment by Resandise** [comment]
> Please have a look here #176

I don't read german

**Comment by Philj030** [comment]
From 176 via google translate-
it is possible to teach Autodrive to stop at closed level crossings

That would be a great improvement

Today I had my tractor and trailer lying next to the road several times on the erlengrad folder because it hits the closed barrier and then it is lifted up and overturned.

I have no problems with it on the French map.
I set the collision height to 2m.
Please check it out with you.

I have the problems on the skin too. The barrier closes, the train comes, which is recognized by the tractor and it stops. As soon as the train is gone, the tractor drives off and tries to get through the barriers. Package on 2m.
That was unfortunately always a problem from AD .. no matter on which map.
Sometimes it works well ... the vehicle stops clean ... but sometimes it doesn't ... but at the latest when the train is gone and the barrier is going to open, the vehicles fly through the pleasure (because they are hanging on the barrier ).
The idea for a solution would be to be able to create a separate point type (possibly waiting point?) For level crossings.
At which AD lets the vehicles wait a few seconds (adjustable) after the collision detection has been canceled (which is triggered at best by the barrier or, in the worst case, by the train).
If stopping works, it should work in such a way that the vehicle will only start moving again when the barrier is open.

Please set the collision height to 1.5 m, then the barriers will be recognized and the vehicle will stop in front of them.
It is still recommended to create a slight wavy line in front of it so that the vehicles do not drive on it at> 100 km / h, braking is then no longer possible.

Folds up: package, 1.75m. I built these "spikes" before and after the level crossing. The tractor drives nice and slowly & recognizes the barriers
