### ISSUE TITLE
Configuração AD com CP

### ISSUE THREAD

**Issue by erksartori** [Stephan-S/FS22_AutoDrive#254]
Boa tarde, venho pedir ajuda.

Eu configurei a minha colheitadeira no CP para colher, e configurei o trator com a caretinha, para ir descarrega-la, no AD. porem acho que não estou fazendo certo, pois o mesmo não vai descarregar fica parado com uma mensagem em vermelho como se não tivesse uma colheitadeira para ele descarregar.

Se puderem me encaminhar imagens de como configurar eu agradeço.
[log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/7884442/log.txt)

**Comment by Iwan1803** [comment]
O debulhador e o descendente devem ter o mesmo objectivo estabelecido no AD para que se possam encontrar um ao outro.
Espero que o tradutor não tenha cometido um erro. O alemão e o inglês são as línguas preferidas aqui.

_The thresher and the unloader must have the identical target set in AD so that they can find each other.
I hope the translator has not made any nonsense now. German and English are the preferred languages here._

**Comment by erksartori** [comment]
Obrigado, agora sim acertei com a ajuda de voces, muito, mais muito obrigado.

**Comment by erksartori** [comment]
Obrigado, agora sim acertei com a ajuda de voces, muito, mais muito obrigado.
