### ISSUE TITLE
Übergabe an CP zum Start der Feldarbeit erfolgt nicht mehr

### ISSUE THREAD

**Issue by TobiHH78** [Stephan-S/FS22_AutoDrive#438]
Die Übergabe von AD an CP scheint gar nicht mehr zu erfolgen, auch nicht bei dem Modus abholen den man z.B. für Sämaschinen oder Düngerstreuer nutzt.

Habe gesehen das der CP Button bei zwei Modi deaktiviert wurde, aber wie gesagt auch bei den anderen Modi scheint es nicht mehr zu gehen. 

Wenn ich einen Düngerstreuer zum Feld schicke und den CP-Button aktiviere, fährt er zwar zum Feld, beginnt aber nicht mit der Arbeit.
Deaktivieren bei dem Modus "Drive" ist auch etwas unglücklich. Das ist ja der Modus um z.B. einen Grubber oder einen Pflug zum Feld zu schicken, der dann aber mit der Arbeit beginnen soll. Das passiert aber nun auch nicht mehr.

[log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/8357506/log.txt)

![1](https://user-images.githubusercontent.com/56259322/160280351-168af8a6-3c71-409c-b126-246f13f03379.PNG)

**Comment by TobiHH78** [comment]
Habe jetzt noch ein paar Versuche gestartet. Das Problem tritt nur noch sporadisch auf, und scheinbar auch nur dann, wenn man die AD Einstellungen vornimmt und den CP-Button schon aktiviert. Wenn man anschließend erst den Kurs mit CP generiert, und als Abschluss dann AD startet, beginnt er am Feld teilweise nicht mit der Feldarbeit.

Macht man es andersrum, sprich erst CP komplett einrichten und dann AD, konnte ich es noch nicht reproduzieren.

**Comment by Axel32019** [comment]
Kann mir nicht vorstellen das es an der Reihenfolge liegt. Eher wahrscheinlich erscheint mir das der Zielpunkt zu weit vom Feld entfernt ist und CP somit das Feld noch nicht erkennt und sich nicht aktiviert.
Zielpunkt näher am Feld probieren.

**Comment by HaploAW** [comment]
I think the issue was AD was trying to start CP using one of the CP job parameter starts. I made a version of AD that just hands over to CP and lets the user set everything in the CP hud / course. There are more improvements on this process I am working / planning. I did implement a delay timer that allows the user to queue up vehicles at a waypoint and hand over to CP after a delay. I found this useful in dispatching convoys to work a field. If they start CP when they get to the destination waypoint, CP doesn't do a good job of collision avoidance when pathing from AD handoff to the start of the course. This delay allows vehicles to get to their destination, wait for a configurable time period (per vehicle setting) and then start CP. This allows CP vehicles in the convoy ahead of the AD controlled vehicle pathing to the course start, time to unfold any implements and lower them. Once on the CP course, collision avoidance is handled by CP.

**Comment by Axel32019** [comment]
Please use latest CP version, this should be fixed already.

**Comment by TobiHH78** [comment]
Problem tritt aktuell nicht mehr auf, dürfte also gefixt sein oder es lag doch am User...
