### ISSUE TITLE
TensionBelts.lua Error with MAN TGX

### ISSUE THREAD

**Issue by alexx2104** [Stephan-S/FS22_AutoDrive#477]
Hello,

since a few days I get with the truck "MAX TGX 580" (https://www.bd-modding.de/post/man-tgx-2020-v1-5-0-0) the lua error mentioned in the subject. I noticed it because the truck does not start and needs a very long time to think. 

Here is an example from the log:

```
dataS/scripts/vehicles/specializations/TensionBelts.lua(1265) : attempt to compare nil with number
2022-04-08 12:13 Error: Running LUA method 'update'.
dataS/scripts/vehicles/specializations/TensionBelts.lua(1265) : attempt to compare nil with number
2022-04-08 12:13 Error: Running LUA method 'update'.
dataS/scripts/vehicles/specializations/TensionBelts.lua(1265) : attempt to compare nil with number
```

Do you have an idea whats going on here?

**Comment by Iwan1803** [comment]
I'm using this and got no errors. As the truck itself has no autoload plattform: which swap bodies are you using?
Also a complete log may be helpful...

**Comment by alexx2104** [comment]
I used it with the LSFM Tanktrailer and the Reisch Agrimaxx, with both followers the error is thrown. I upload the complete Log later.

**Comment by Iwan1803** [comment]
Try the swap bodies from BD-Modding itself. With them i've got no problems.

**Comment by alexx2104** [comment]
I don't use swap bodies. I only use the TGX 850 vom BM Modding (only the truck!)

I just did a test. I just wanted to send the truck to field 72. Long time to think, then he drove off sometime after about 30 seconds.

I had something like that with the Claas Arion (is vanilla in the game).

Here's the log:

https://gist.github.com/alexx2104/ce373f418ae6a9dda6a53ac03d1dffea

**Comment by Axel32019** [comment]
Hello @alexx2104 , I could see min. 5 Maps in the mods -> always a risk for issues. Use only 1 Map per game!
FS22_New_Bartelshagen_2022
FS22_NF_Marsch_4fach
FS22_NF_Marsch_4fach_oG
FS22_noMansLand
FS22_The_Old_Stream_Farm

Not sure if the root cause migth be the FS22_NF_Marsch_4fach_oG - I do not use this Map:
2022-04-08 13:59 C:/Users/a.buerger/OneDrive/Dokumente/My Games/FarmingSimulator2022/mods/FS22_NF_Marsch_4fach_oG/effects/belt/beltMeshes_materialHolder.i3d (8.61 ms)

Try the following:
- remove the additional maps
- remove FS22_VehicleControlAddon, which seem to do something with belts
- try another Map than FS22_NF_Marsch_4fach_oG

Autodrive only touch the belts 1 time if unload an AutoLoad vehicle, not multiple times in sequence.

**Comment by alexx2104** [comment]
I tried another map (Elmcreek), worked. Nf marsch og new savegame, worked.

Then I just bought a new TGX 580 in my main savegame. And what I should I say: it worked. So I just sell the old on and use the New one🙈

**Comment by Iwan1803** [comment]
Neuer Release / new release: 
https://github.com/Stephan-S/FS22_AutoDrive/releases/download/2.0.0.6/FS22_AutoDrive.zip
