### ISSUE TITLE
AD - Follow combine driver still going into fruit, and sometime blocking combine

### ISSUE THREAD

**Issue by Chico0008** [Stephan-S/FS22_AutoDrive#515]
HI

using CP 7.0.1.14 and AD 2.0.0.5
when having 2 combine (or more) working in fields, AD driver usualy drive inside fruit (despite having the no drive on fruit enabled)

+, when driver need to unload, still going inside fruit and soemtime set in front of a combine, blocking it just set here without moving or going backward

Driver should always avoid fruit event when going to unload, and have a better detection to avoid combine (working or manoeuvre)

**Comment by Axel32019** [comment]
Hi @Chico0008 , Please add some screenshots which show the situation.

**Comment by Chico0008** [comment]
got better than screenshot ;)

Driver don' take care of other driver
https://drive.google.com/file/d/1oW9uSd8-qELxeWFiuDrBk1zRnkDuLuzW/view?usp=sharing

Driver drive in fruit to catch combine
https://drive.google.com/file/d/1huYegBeFvyTM6KwWMgh22FXBlpoY6wPE/view?usp=sharing

i tried to activate debug before this happen, driver was waiting because he couldn't seem to find a path, when i deactivated debug channel, he started to drive immediately
When debug was activated, he was calculating to avoid fruit, but maybe the path calculated was too long ?!

i'm playing on No Man's Land on a very big field (45,7 Ha)

and finally, when the driver needs to unload, same, running through fruits again :/
https://drive.google.com/file/d/1mFJ8qi1S8XS4jG2V1DVdhGqpAoQmLkdj/view?usp=sharing

**Comment by rohne83** [comment]
afaik, when avoid fruit is activated AD first tries to calculate a path which indeed avoids it. But if it cannot find one within reasonable time, it will try to calculate ignoring the fruit. Think that's what happened in your videos. Start point of the unloaders far away from your combines. You should move that point so that a fruit avoiding path can be calculated quicker. And use a more appropriate pattern for the combines' field rows (best so far is lands) which will help not only your combines to have the fruit outside the fruit everytime but also your unloaders.
In your last video there just wasn't any other way to leave the field as there was fruit everywhere and leading combine still not finished the lane where your unloader could have left.

Issue in your first video instead is problematic indeed. CP unloaders in FS 19 where amending their paths just-in-time when collisions with other drivers where expected. Maybe AD could include such pathfinder enhancements as well anytime.

**Comment by Axel32019** [comment]
Driver drive in fruit to catch combine
-> what is the setting for Pathfinder factor? For large fields it needs to be increased step by step
i tried to activate debug before this happen, driver was waiting because he couldn't seem to find a path, when i deactivated debug channel, he started to drive immediately
-> debug setting has no influence here, only size of field, settings etc.
and finally, when the driver needs to unload, same, running through fruits again :/
-> during path calculation I can see status with 1/2, means your settings do not have fruit avoid etc. so check this!
