### ISSUE TITLE
AutoDrive Interface to remember previous setting

### ISSUE THREAD

**Issue by RobTomcat** [Stephan-S/FS22_AutoDrive#619]
Can we please have an option to keep AutoDrive well behaved and stop AutoDrive being always open when you start a game.  Courseplay remembers its previous setting so why can't AutoDrive?  

Yes, I know Alt+0 hides the interface but if I close the AutoDrive interface it should not be open the next time I load FS22.  It is really annoying to have to go through each vehicle pressing Alt+0 each time you start FS22.  Alternatively, if this feature is already present, please tell me how to enable it.  Thanks.

**Comment by Tensuko** [comment]
https://github.com/Stephan-S/FS22_AutoDrive/releases/tag/2.0.0.7 ?

**Comment by RobTomcat** [comment]
I have been running 2.0.0.7 since it came out on Github.  No change to my original request.

If the feature is present in 2.0.0.7 to stop the AutoDrive interface automatically opening for every vehicle each time I start FS22, please tell me how to enable it as I don't see it.  Thanks.

**Comment by cwattyeso** [comment]
Yeah I too having been having this issue with Autodrive since a few updates ago. Everytime you launch the game, load or reload a save all the vehicles have the Autodrive Hud Open on them and this was not the case with earlier versions of Autodrive at the beginning of the year. I was hoping this issue would be fixed in the most recent Autodrive version when the issue of Autodrive not saving user settings got fixed such as Hud Size and Position. However the always open on load option does not appear to have been fixed and is still present and it's really annoying.

**Comment by Axel32019** [comment]
#765
