### ISSUE TITLE
CUTTING CORNERS

### ISSUE THREAD

**Issue by Vancleef69** [Stephan-S/FS22_AutoDrive#621]
I have notice in the latest release that autodrive is cutting in on corners and not following the waypoints like it used to.

**Comment by Tensuko** [comment]
Maybe its your network?

**Comment by venquessa** [comment]
Autodrive has a path finder element.  It will smooth out courses and cut corners.    Does it in single player too.  It's not normally an issue, but can be.

To remedy it, add a few more waypoints and bunch them up together, that pretty much forces the pathfinders hands, so to speak.

It's also EXACTLY why the "generate curve" feature was so needed, as it forces the pathfinder to actually follow the sequence of dots, rather than guessing how to make the turn from a single 90* waypoint change.

If along a course AD sees a single way point is off set to the left, it might start turning towards it, but looking ahead to the next it will see the course just comes back and so it stops turning and cuts straight across.

Examples were it causes issues.  If you have a single waypoint aiming to force a tractor out for position before turning into a gate or production dump area (say) lined up, ADs path finder element and look ahead will filter it out mostly, cutting across and probably fouling on said gate or obstruction.

Again the solution is to put a sequence of waypoints in a compressed bunch.  Note, compression waypoints also "usually" slows vehicles down.

**Comment by Iwan1803** [comment]
As no further feedback -> closed!
