### ISSUE TITLE
AD combine unloading issues

### ISSUE THREAD

**Issue by kwguk** [Stephan-S/FS22_AutoDrive#638]
Firstly i love AD, its great. But when it comes to relying on it to unload combines in the fields its seriously flawed. Perhaps it because im comparing it to when CP used to unload combines and did it on the whole very well. 
Firstly when it finally catches up a with a fully loaded combine it will remain stationary even though the combine CP is set to unload on the move.
 It takes an age for the tractor to react to a call from combine. It will trundle after it then usually stop and wait until the combine itself has filled up and stopped. I get 'waiting for room' then 'waiting for call' even though the tractor has already responded. Its all very frustrating.
The CP team have said the failure to move when unloading a fully loaded combine is a AD problem.

**Comment by rohne83** [comment]
Now that CP has the unloader mode back, you might try out that one. This can be used for normal unloaders as well, handing over to AD or Giants helper for transporting the grain to the silo or sell point.
The mentioned points still remain valid if combine is driven by AIVE, Giants helper or player though. But regarding the time to react on the call, you have to take in mind that the AD driver doesn't know anything about the combine. It doesn't know how long the combine will keep going in the same direction, when it will be at which fill level, when it will turn, in which direction it will turn, etc. It just knows its current position, fill level and driving direction and has to use just this information to calculate a path to and manage the driving whilst unloading the combine. And therefore, for a lua script, it's doing its job quite well. CP unloader has much more information about the CP-driven combine and pathfinding is an integral part of CP, so you cannot expect AD to become as efficient as CP with this task. When you engage AD, you will see that it nearly always reacts on the call at the right time, but ofc it needs some time to calculate and then drive the path. You can see it in the top line of the AD hud. If it doesn't get called at all or stops approaching the combine, this will most likely be because the combine fill level already reached the 80/90% thresholds (see #640 for this).
Don't know if the refuse to move on again once the combine had to stop because of fill level can be fixed or is even intended to be fixed. This AD behavior was already seen in FS 19.

**Comment by Iwan1803** [comment]
No further feedback -> closed!

**Comment by coatsy35** [comment]
> No further feedback -> closed!

This is still an issue
