### ISSUE TITLE
Unloader reversing instead of driving to combine

### ISSUE THREAD

**Issue by iljarogoff** [Stephan-S/FS22_AutoDrive#640]
first, sorry for my language, I am not english native speaking.
I often have the problem, that AD unloading a combine is very strange. When AD tries to get to combine, it suddenly stops and driving backwards, intead of driving to combine. What is the reason? Why happening?
I made a video of it to make it clearer. Log attached.
[]Video (https://www.youtube.com/watch?v=RKNSVXHQ65Y)
[log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/9225903/log.txt)

**Comment by BonaXJ6** [comment]
I have exactly the same problem! 
I had already asked for a solution in Discord.

**Comment by kwguk** [comment]
yep i have the same experience

**Comment by rohne83** [comment]
As per Iwan1803 in Discord, the unloading approach is cancelled if combine reaches 90% fillgrade. So seems the situation in the video is works as designed. Question rather is, why AD devs felt this behaviour is necessary at all. Cannot imagine a situation so far where this would make sense.

**Comment by Martin-L45** [comment]
@rohne83 Could this be to make sure if there is room if the combine has to reverse to make a pocket ? (auger in crop)

**Comment by iljarogoff** [comment]
Not in the situation as in the video. There is no need to build a pocket here because the pipe is not in the fruit

**Comment by JustDen1234** [comment]
Same experience here. No need to backup, combine is standing still to be unloaded, but unloader suddenly stops, and backups ("making room")

**Comment by andreasthu** [comment]
same here, this was necessary at first row, but not infield.
another situation is near the end of the row,
the unloader stops and wait, when the combine is near the end of the row.
i think it were better the unloader drive to the combine and unload them also at the end of the row.

a 2nd problem, if the cp-combine is full and stops for waiting to the unloader, the ad unloader get under the pipe, but the combine wait as he is empty, he should beginn to harvest suddenly the ad unloader is under the pipe, the cp setting is "no stop while unload"

lg
andreas

**Comment by rohne83** [comment]
could imagine the 90% fillgrade threshold for stopping the approach to the combine, is to prevent the unloader from being to near to the combine before it creates its pocket. But the more appropriate solution to prevent this would be to not approach the combine at all when it will have to create a pocket (as requested in #572, to have AD not ignore the CP settings and instead only unload when CP tells there's no fruit under the pipe and we're not in first headland lane).
Doesn't make any sense to stop the approach just because the combine is 90% full - on field rows that's when its most urgent to not loose any additional time. And I noticed, when reengaging the AD unloader this threshold seems to be at 80%, coz I never managed to get the unloader go to the combine when I engage it while combine already has 80% or more.

And of course, the two points that andreasthu mentioned. Once full combine reached, the combine should start to drive again if it can (CP knows better than AD when it can and when not, working perfectly when you drive the unloader manually). And at the end of the row it should continue unloading until combine is empty and only then move backwards out of the way (also working perfectly already when unloading manually: CP combine waits at the row end until unloading finished and only afterwards it starts its turn).

**Comment by kwguk** [comment]
> Few days before CP released their unloader mode, I managed to get rid of the 80 and 90% thresholds in AD myself (was a bit hard to find the right way, as in the end it had to be amended in CathCombinePipeTask.lua, CombineUnloaderMode.lua, FollowCombineTask.lua and even three comparison lines of HarvestManager.lua) but it then worked like a charm at least for me. Preferring the CP unloader now when combine's are driven by CP, I hadn't opportunity yet to test it in further situations. But still think it's worth to at least think about eliminating this threshold.

Any chance of you showing exactly which lines to edit? Id be more than happy to test it for you

**Comment by coatsy35** [comment]
> Few days before CP released their unloader mode, I managed to get rid of the 80 and 90% thresholds in AD myself (was a bit hard to find the right way, as in the end it had to be amended in CathCombinePipeTask.lua, CombineUnloaderMode.lua, FollowCombineTask.lua and even three comparison lines of HarvestManager.lua) but it then worked like a charm at least for me. Preferring the CP unloader now when combine's are driven by CP, I hadn't opportunity yet to test it in further situations. But still think it's worth to at least think about eliminating this threshold.

Do you still have the code to fix this? are you willing to share it?

**Comment by Iwan1803** [comment]
Duplicate to the mentioned topic -> closed!
