### ISSUE TITLE
Default HUD Visibility

### ISSUE THREAD

**Issue by coder2000** [Stephan-S/FS22_AutoDrive#666]
Is it possible to configure the default hud visibility? I like using the hud but don't want it on all the time. It can get frustrating to have to always turn it off when starting to play again and getting into a vehicle for the first time.

**Comment by magicmana** [comment]
if can  help 
with "popup" window the best way i had found,  is to assign de open/close windows to  a single key
for sample on my  keyboard i have :
F10 = open/close courseplay hud
F11 = open/close autodrive hud
F12 = open/close vehicle explorer hud
after a few time to learn key , it's easy to close popup windows that you don't want ;-)

**Comment by coder2000** [comment]
I know how to manually do it but it would be nice if it didn't have to be closed every time.

**Comment by cwattyeso** [comment]
Yeah this has been a gripe of mine since several updates ago when this Hud behaviour first appeared in game, where everytime you load a save or connect to a server, the hud is open on every single vehicle and you have to go round every vehicle and close it. Can we not just have the Hud closed by default and have us players open it as and when we need it?

**Comment by Inoque71** [comment]
Hi, I active again 'set XML Boolean' on showHub to get "True/False" on AutoDrive_config.xml. This will affect anything with this new version 2.0.0.7
Regards

**Comment by Axel32019** [comment]
#765
