### ISSUE TITLE
Covers Wont Open On Trailers

### ISSUE THREAD

**Issue by Dadx5Gaming** [Stephan-S/FS22_AutoDrive#702]
Using Autodrive in a shared public server, I am unable to open any trailer covers or close them in game.  However, if I switch to another members farm, I am able to do so.  Same trailer model and everything.

I have tried resetting keybinds, removing keybinds, creating a new farm and joining it, but its always tied to me and when I try to use covers to load items into trailers.

**Comment by Iwan1803** [comment]
And why do you think it's an AD related problem?

**Comment by Dadx5Gaming** [comment]
Because when I remove AD from the server I use the covers without any issues.  Readding AD makes the issues return.

**Comment by davidlandry2019** [comment]
@Iwan1803 or any moderator - It would be good to have an answer to @Dadx5Gaming question.  The issue is able to be reproduced easily from his end.  Can you provide some useful steps that your user base can help provide troubleshooting data for it to be investigated?

I believe step 1 has been done which is removing courseplay and his issue with the covers is not present.  Re-adding your courseplay product presents the issue with the covers.  

If you can reply to the thread with other useful steps to further nail down the issue it would be great.  Also what other information would you like to see in order to troubleshoot this item.

Thanks,

**Comment by Axel32019** [comment]
First step would be to add the log's from the server and the clients.

**Comment by davidlandry2019** [comment]
Ok great can we get someone to post the process of which files to upload and where they are kept?

**Comment by Iwan1803** [comment]
No further feedback, no logs -> closed!
