### ISSUE TITLE
Multiple combine unloaders, call the one with "less" empty space?

### ISSUE THREAD

**Issue by manierim** [Stephan-S/FS22_AutoDrive#713]
Hello,

currently using AD v. 2.0.0.7 and CP 7.1.1.4. 

One harvester running a CP course.

2 truck with trailers running AD combine unload.

Looks like that when the combine is full the closest "waiting for call" unloader is selected. Sometime there is already an unloader parked in the field with some load from previous unload sessions and it is ignored being to far away.

Would it be possibile to have a "per harvester" setting to choose between calling the closest awaiting unloader and the "fullest" one? This would make sure an unloader "100% used" before "calling a new one"....

**Comment by rohne83** [comment]
If I remember correctly there already is an issue here exactly for this.

**Comment by rohne83** [comment]
found the issue: #663 it's in German though, but exactly for the same topic

**Comment by Iwan1803** [comment]
Does it make sense that the combine has to wait 5 minutes instead of 30 seconds for the unloader just because the fuller one is called?
There will always be situations where calling the nearest or an other unloader makes more sense. AD is a script, not an AI.

**Comment by manierim** [comment]
I was suggesting a setting not an automatic choice..

**Comment by Iwan1803** [comment]
How often do you want to change this option? After every or 2nd unload? In my eyes this makes no sense.

**Comment by rohne83** [comment]
But it also doesn't make sense that the harvester during chopping is calling the next unloader in a turn, just because the current unloader shortly lost the assignment to the chopper in this turn (happens quite often unfortunately) and the next one's parking position is a few meters nearer to the chopper than the current unloader.
And also during combine harvest, it rather depends on field size. On larger fields, ok, having multiple unloaders distributed at various positions of the field and calling the one which is the nearest ist totally understandable. But on smaller fields (less than 10-20 hectars depending on field shape and various other conditions) where you just need several unloaders because of the long way to the silo, you would normally want to have one unloader filled completely and going off to the silo before the next one is the one to be called. Cause then it can happen that you have 2 or more unloaders all with 75% fill level on the field and no real free capacity left. Those last percents get filled up quickly on every unloader and all unloaders will be on the way to the silo about the same time - and none left for offloading the combine again.

**Comment by Iwan1803** [comment]
No further feedback -> closed!
