### ISSUE TITLE
Unload harvester not working for Case harvester (or header)

### ISSUE THREAD

**Issue by flyhard** [Stephan-S/FS22_AutoDrive#870]
I am using a Case Axial Flow 9250 on Haut bereylon with the Case 3162 TerraFlex Draper 45FT header. 

When the unloader is called. It comes, but stays out of range of the pipe, so it just keeps trying to unload but never succeeds.

**Comment by Axel32019** [comment]
Screenshots with Debug Sensors would help.

**Comment by lordbanastor** [comment]
I've got the same issue. Here's the screenshot with the debug. Hope this is what you need. 
![LogAutoDrive_001](https://user-images.githubusercontent.com/103431999/227773391-cd3f8d77-292d-44d0-80b0-c85209b318bb.jpg)

**Comment by Axel32019** [comment]
No, enable debug sensors, close AD menu, let unloader reach harvester -> screenshots...

**Comment by Axel32019** [comment]
no update -> closed

**Comment by Oberlump** [comment]
Same Problem here. Maybe the screenshots help?

![fsScreen_2023_10_31_10_36_03](https://github.com/Stephan-S/FS22_AutoDrive/assets/70055950/78219085-aac8-4f4b-9dc7-960f63c8e2ec)
![fsScreen_2023_10_31_10_36_19](https://github.com/Stephan-S/FS22_AutoDrive/assets/70055950/6d66c417-ad87-4db5-bc94-1395d27c0c4d)
![fsScreen_2023_10_31_10_36_42](https://github.com/Stephan-S/FS22_AutoDrive/assets/70055950/cb07ee5b-0d04-4d90-9d5e-f9a239e3b0de)

**Comment by Oberlump** [comment]
Additional Information:

I have also tested several times whether it helps to reduce the “pipe distance” setting. Then unloading usually works once because the driver drives closer to the harvester. But then it doesn't work again. I tested e.g. -0.1m. Sometimes the driver drives in circles (like on the screenshots) 3-4 times and only then does he get close enough to the thresher for unloading to work.

The problem really only exists with this harvester.

If you set "Stop while unloading" to deactivated in Courseplay so that you want to unload while driving, Autodrive will also drive in front of the harvester and across the cutterbar immediately after unloading starts.
