### ISSUE TITLE
Stopping vehicles 

### ISSUE THREAD

**Issue by Ericd22b** [Stephan-S/FS22_AutoDrive#910]
Hi I saved my game when I had to routes blocked since then iv removed the offending vehicles but every vehicle still stops on the routes as if the block is still there 
![20230519_140654](https://github.com/Stephan-S/FS22_AutoDrive/assets/57689373/38e63339-63a8-4aa0-9d34-05e1d4301ee6)
![20230519_140700](https://github.com/Stephan-S/FS22_AutoDrive/assets/57689373/703dfd4e-56d8-4463-98c1-ed4c00ae4b5a)
![20230519_155711](https://github.com/Stephan-S/FS22_AutoDrive/assets/57689373/b720508c-ac8b-4efe-a97e-4688b197de28)
![20230520_135202](https://github.com/Stephan-S/FS22_AutoDrive/assets/57689373/6682df2a-e020-4a26-a2b1-fdd6c2accf5b)
![20230520_135212](https://github.com/Stephan-S/FS22_AutoDrive/assets/57689373/115670f2-79bd-4f88-98ff-a08572388b02)
![20230520_141324](https://github.com/Stephan-S/FS22_AutoDrive/assets/57689373/55d88785-e8dd-4403-a34c-88903943421c) hope the pictures help

**Comment by realskudd** [comment]
I've been having this issue today as well. I'm on the Lazy Acres map and am using all my own recorded routes.  For no reason that I can see whatsoever, various vehicles will just stop mid-route, or will slow down dramatically like they're going to turn when in fact they're on a relatively straight line route.

For what it's worth, I'm running the latest release version 2.0.1.4 on PC. Not sure if this is a PC-only mod, but figured I'd mention it at least.

**Comment by realskudd** [comment]
Example: https://i.imgur.com/l9uAkSa.mp4

**Comment by realskudd** [comment]
Oh, and here this combine just stopped for no reason whatsoever.

![image](https://github.com/Stephan-S/FS22_AutoDrive/assets/4642150/fe051068-1e44-4542-9537-d1c85947638b)

**Comment by Axel32019** [comment]
@Ericd22b , @realskudd Enabel debug sensors to see what is blocking.

**Comment by Axel32019** [comment]
@realskudd More easy in AD Menu:
![910](https://github.com/Stephan-S/FS22_AutoDrive/assets/52026009/1e0eaac3-c5e2-4ceb-bf27-d186a07d7bca)

**Comment by realskudd** [comment]
I don't have glasses like that in the AD menu system,

![image](https://github.com/Stephan-S/FS22_AutoDrive/assets/4642150/e9397522-49f5-4cc2-8c31-c4582df11f7d)

**Comment by realskudd** [comment]
I don't mind setting it up in the xml file. I am a software engineer by trade.

**Comment by Axel32019** [comment]
The it should be no problem for you to change game.xml:
```
    <development>
        <controls>true</controls>
```

`<console enable="true"/>`

**Comment by realskudd** [comment]
Danke. 

I left my game running overnight before I changed this, then reloaded the save that was having trouble. While I didn't get to where it was failing before (from my video), the route it was on was ocasionally giving a red box ahead of the truck on a straight line, but only every so often. I'm having to fully restart the game now though, because I don't get a framerate above like 12 fps for some reason. I don't think that's related to AD.

I haven't looked to closely into the code, but is there a concept of "rotation" or "heading" of a node in a path? That's the only thing that would make sense to me, as it would cause the vehicle to see it and think "uh, no.. I can't do a 180 degree turn in the middle of a straight line".

Just my initial thoughts.

**Comment by realskudd** [comment]
Okay, so I have watched the trucks as they follow a route, and here's what I've found.

Smaller/slower vehicles have no trouble with it, and they will follow the route at full speed. It's the larger, faster, heavier vehicles that have trouble. I've set the look-ahead distance to 8m in an attempt to help with it, but it doesn't seem to do anything positive.

One thing I noticed is that when the nodes are closer together than 8m, the vehicle has no trouble maintaining a reasonable speed. But when the nodes are further apart, as when recording a straight path spaces them apart quite a bit, the look ahead is not sufficient to find the next node, so the vehicle slows until the next node is within the look ahead box.

I see this as being able to be fixed a couple of different ways:

1. Allow for greater look-ahead distances
2. When crossing a node, look 2 nodes ahead and determine if they're of safe traveling speed
    - It seems like this isn't being done, and only the next node in the box is considered

I can provide another video clip if it would help. Or if you would like for me to provide further details of my analysis, I'd be happy to.

**Comment by realskudd** [comment]
Here's another scenario of it happening, though this one makes far more sense.

On a different map, using a route I had _just recorded_ with this vehicle, it's unable to follow the path because it thinks there's a collision ahead.

![image](https://github.com/Stephan-S/FS22_AutoDrive/assets/4642150/2b854492-1b23-4703-b1bb-adcbfdb18cfc)


I think it's probably related to some trouble I've been having with manually adjusting the route in this section of the network because the road is not being seen as ground for the purposes of driving or route construction, but is for the vehicle's movement and where AD plots the route when recording.

![image](https://github.com/Stephan-S/FS22_AutoDrive/assets/4642150/7fada7ff-877a-473b-8529-648a36835bbb)

**Comment by realskudd** [comment]
I've been able to change the behavior by adjusting the "Collisionheighth Over Ground" value. For some reason it was set to 1.25m instead of what it said the default was (2m). That did improve some of the initial issues, but now I'm seeing what looks like a refusal to go somewhere that is outside of some threshold around that value when the sensor box is well above ground. Perhaps it's a situation where the path finder is unable to determine where to go since it appears to be attempting to leave the ground?

![image](https://github.com/Stephan-S/FS22_AutoDrive/assets/4642150/78c5f4ca-3729-49a5-9070-47fbb2ee6057)

Prior to this, it refused to climb the ramp into this drop off location. When I changed the value to 2m and tried again, it would get this far and stop.

**Comment by realskudd** [comment]
https://youtu.be/QIb-IJnvQ-I

**Comment by realskudd** [comment]
Seems like this might be related to #211, #587

**Comment by realskudd** [comment]
I did raise the value to 2.5m and it seems to have fixed all those scenarios I mentioned today. I think the comment about having multiple hitboxes raised in #587 might be something to consider though. In such a scenario, comparing height of the leading edge to the height of the trailing edge of each box might be worthwhile. Then you could implement a couple more user-tweak-a-ble parameters: maximum hit boxes, minimum hitbox depth, maximum hitbox depth.

**Comment by realskudd** [comment]
![image](https://github.com/Stephan-S/FS22_AutoDrive/assets/4642150/f1929f76-1aaa-4693-bc8e-836c5e305e36)
![image](https://github.com/Stephan-S/FS22_AutoDrive/assets/4642150/2e8381d2-d9e9-4233-992d-7f84b6a78ad7)
![image](https://github.com/Stephan-S/FS22_AutoDrive/assets/4642150/c961254e-2aa8-4bd3-be36-ee89d793034f)


Sigh. More inexplicable stopping. I don't understand why this is stopped. There's no colision, it's a ground surface, and it's following a path that I had _just now_ recorded with the same vehicle/implement combination.

**Comment by regs1980** [comment]
@realskudd Post AD settings via screenshots.

**Comment by Axel32019** [comment]
> ![image](https://user-images.githubusercontent.com/4642150/284369646-f1929f76-1aaa-4693-bc8e-836c5e305e36.png) ![image](https://user-images.githubusercontent.com/4642150/284369670-2e8381d2-d9e9-4233-992d-7f84b6a78ad7.png) ![image](https://user-images.githubusercontent.com/4642150/284369879-c961254e-2aa8-4bd3-be36-ee89d793034f.png)
> 
> Sigh. More inexplicable stopping. I don't understand why this is stopped. There's no colision, it's a ground surface, and it's following a path that I had _just now_ recorded with the same vehicle/implement combination.

Picture 1: Feel free to ask Giants why a selling point has the same collision as a TREE!!!
Solution: In AD settings change collision detection to OFF or FS19, NOT FS22.
