### ISSUE TITLE
Wunsch: Bestimmbare Lademenge aus Silo

### ISSUE THREAD

**Issue by AndyBCoast** [Stephan-S/FS22_AutoDrive#973]
Hallo,

ich würde es begrüßen, wenn es mal die Möglichkeit geben würde, bei der Funktion Be- und Entladen eine Füllmenge vorgeben zu können. Somit müsste nicht immer der ganze Anhänger gefüllt werden, wenn nur die Hälfte benötigt wird. Gerne auch in Verbindung mit der multiplen Fruchtwahl.

**Comment by coatsy35** [comment]
That is a good idea. I have this issue when running lots of contracts and filling at the Meridian storage yard with say fertiliser or seed. It would be nice to send them back to only fill up with so much. Saves having to then empty it all out into bags later.

**Comment by ThomasMatern** [comment]
Dealing with actual fill volumes would be a pain because then we would also have to deal with units. However, specifying a fill level as a percentage would be more straightforward. Mockup:
![fill-level](https://github.com/Stephan-S/FS22_AutoDrive/assets/8754844/9b0828db-2332-48f4-b500-42fe4b6f2e1f)
@Iwan1803 @Axel32019 thoughts?

**Comment by Iwan1803** [comment]
@ThomasMatern check the mod "Fill Level Limiter". It is not compatible with AD buty maybe you could find an answer there.
However, the routines for the fill level would then also have to be adjusted, because if, for example, 100 liters does not correspond to the minimum fill level, AD would not continue. I see more difficulties than benefits.

**Comment by Axel32019** [comment]
@ThomasMatern Yes, thoughts...
User expectations, more complex GUI, complex implementation....

**Comment by JSGER** [comment]
You can use the mod FS22_FillLevelLimiter.

**Comment by Iwan1803** [comment]
This will not work as the mod is not compatible to AD.

**Comment by Iwan1803** [comment]
No further feedback -> closed!
